### ISSUE TITLE
Japanese/Chinese characters in video titles

### ISSUE THREAD

**Issue by DeGlad** [Booplicate/MAS-Submods-YouTubeMusic#10]
Hello there, I installed the submod just today and I happened to come across a problem with titles that contain Japanese/Chinese characters.

When I installed the submod everything was working perfectly, that was until I tried playing a song that contained Japanese characters in its title. The options that came up contained some weird characters and were basically unreadable. I clicked on the first option and the song I was actually searching for played without any problem. 

Thank you in advance!

**Comment by Booplicate** [comment]
The first 3 positions are almost always that you were looking for. But this'll be fixed in the next release, thanks for the report!

**Comment by Booplicate** [comment]
Closing as completed, this will be in in the next release (which is soon).
