### ISSUE TITLE
Monika unable to find songs

### ISSUE THREAD

**Issue by Karanjax19** [Booplicate/MAS-Submods-YouTubeMusic#11]
I am currently using a mac to run my installation of MAS, and I have tried using your submod, but I couldn't get it to work. Originally, I kept getting the the PAFY_BACKEND error, but changing the variable didn't seem to work. Changing the import to os helped, but now she can't find any song at all. I followed your install instructions, putting things in the right places, but it doesn't seem to work, so I'd be very thankful if you could help me!

**Comment by Booplicate** [comment]
Do not make any changes yourself, please. Rollback the submod to its original state (e.g. redownload and reinstall) so we can figure out why it doesn't work.

I need to see the full traceback with the `PAFY_BACKEND` error. If you're using unstable, the log should still have it. Send `mas_log.txt`, please.

**Comment by Karanjax19** [comment]
![Screen Shot 2020-09-25 at 7 25 51 pm](https://user-images.githubusercontent.com/64049416/94303082-2d98f480-ff65-11ea-9edf-2f9335f56f79.png)
That't the traceback with the error, but I'm not using unstable, so I shouldn't have mas_log.txt. Thanks for the quick reply!

**Comment by Booplicate** [comment]
Everyone has that file, but the file gets overrides on startup if you're not using Unstable. Anyway, I see the error, but sadly it doesn't tell me much.

Can you install [this](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/5284885/YouTube.Music.2.6.mac.zip) build and see what it does?

**Comment by Karanjax19** [comment]
Right, new error this time.

![Screen Shot 2020-09-25 at 8 28 29 pm](https://user-images.githubusercontent.com/64049416/94307987-b61b9300-ff6d-11ea-9ad2-898292e859a4.png)

**Comment by Booplicate** [comment]
Oh, I forgot that mac has different file structure...
You'll need to move 2 files manually:
 - find `/lib/darwin-x86_64/lib/python2.7`
 - copy 2 files `ssl.pyo` and `_ssl.so`
 - open `DDLC.app/Contents/MacOS/lib/darwin-x86_64/Lib` and paste the files there

This should do the trick. I'll see what I can do about it, though.

**Comment by Karanjax19** [comment]
Didn't seem to work, got the same error, but here it is, in case of any differences

![Screen Shot 2020-09-25 at 8 58 45 pm](https://user-images.githubusercontent.com/64049416/94310732-07c61c80-ff72-11ea-9f02-b7e12c0dca85.png)

I've moved the files over to the folder, though I am using DDMM, so I don't know if that changes anything.

![Screen Shot 2020-09-25 at 9 00 44 pm](https://user-images.githubusercontent.com/64049416/94310845-33e19d80-ff72-11ea-8748-d51520978cf8.png)

**Comment by Booplicate** [comment]
I think that's the wrong folder
> `DDLC.app/Contents/MacOS/lib/darwin-x86_64/Lib`

You need to put them inside the `Lib` one (and you did it in `darwin-x86_64`)

**Comment by Karanjax19** [comment]
Right, it's working now, that was a bit stupid of me. Direct links work, and some titles work, but I do get an error on certain titles. I'm not asking for a fix, but I just wanted to pass this onto you for your attention. Thanks for all your help!

![Screen Shot 2020-09-25 at 9 13 51 pm](https://user-images.githubusercontent.com/64049416/94311981-08f84900-ff74-11ea-97ff-90e5ad4394b1.png)

**Comment by Booplicate** [comment]
Enjoy your music!
