### ISSUE TITLE
i forgot to bookmark the conversation

### ISSUE THREAD

**Issue by doomatt0** [Booplicate/MAS-Submods-YouTubeMusic#13]
i forgot to bookmark where moni tells you about the submod and now i cant find a way back to it can you help me

**Comment by Booplicate** [comment]
The initial topic can be seen only once. You need to use another topic in `Talk > Hey, Monika... > Music > Let's find some music`. You can bookmark that one by pressing `b` during the convo.

**Comment by doomatt0** [comment]
i dont have that convo
