### ISSUE TITLE
Monika takes a long time to load music 

### ISSUE THREAD

**Issue by CloakedGhost** [Booplicate/MAS-Submods-YouTubeMusic#16]
Hey there, I have the YouTube music submod installed and I really love it. But for some reason, Monika takes a long time to search for a song and play it. It can take up to 10 minutes. My internet connection is stable, I have 400 mbps according to speedtest. So is something "limiting" or interfering with Monika?
Thanks in advance.

**Comment by Booplicate** [comment]
I'm not sure, I do not limit speed during downloading, although, the submod will try to download the highest quality available for the best experience. Nevertheless it shouldn't take so long.

**Comment by CloakedGhost** [comment]
So could something on my PC be at fault? Sorry I know you don't know what's on my PC, but do you know any programms/settings etc. that could potentially "interfere" with the submod in some way?

**Comment by Booplicate** [comment]
Not really, should be fine even if you use VPN/proxy. Are you running the latest (`2.10`) version?

**Comment by CloakedGhost** [comment]
Yes.

**Comment by CloakedGhost** [comment]
It works now after a windows update. I don't know why that fixed it, but I'm glad it works properly now. Thanks for the help!
