### ISSUE TITLE
An exception has occured

### ISSUE THREAD

**Issue by CloakedGhost** [Booplicate/MAS-Submods-YouTubeMusic#17]
Hey it's me again. I got an error message after trying to play a song and now it doesn't work anymore. I always just get this:

Full traceback:
  File "game/script-ch30.rpy", line 1475, in script call
  File "game/event-handler.rpy", line 2516, in script call
  File "game/Submods/YouTube Music/ytm_topics.rpy", line 158, in script call
    call .ytm_process_audio_info(_return, add_to_search_hist=False, add_to_audio_hist=True)
  File "game/Submods/YouTube Music/ytm_topics.rpy", line 211, in script
    $ ytm_utils.addAudioHistory(
  File "D:\DDLC\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\DDLC\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/YouTube Music/ytm_topics.rpy", line 212, in <module>
    ytm_globals.YOUTUBE + ytm_globals.WATCH + audio_info["id"]
TypeError: 'NoneType' object has no attribute '__getitem__'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.1

**Comment by Booplicate** [comment]
That happens when you enter a song that doesn't exist (probably invalid URL). It's already fixed, I just never released it. You can ignore the error for now, it's harmless.

**Comment by CloakedGhost** [comment]
I see but I didn't enter a URL. I told her the song name and clicked on it from the selection, yet I always got this error message, no matter what song it was. When I turned on the PC today though, it worked again for some reason. Really weird.

**Comment by Booplicate** [comment]
Oh, I probably need to update the lib I use. Thanks for the report!

**Comment by Booplicate** [comment]
Can you send your `submod_log.txt`?

**Comment by CloakedGhost** [comment]
Sure, here it is
[submod_log.txt](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/6265190/submod_log.txt)

**Comment by Booplicate** [comment]
Alright, the latest update should fix this. Can you confirm?

**Comment by CloakedGhost** [comment]
Yes it works now, thank you!

**Comment by Booplicate** [comment]
Nice!
