### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by zwartkop2** [Booplicate/MAS-Submods-YouTubeMusic#18]
I extracted the zip to the /DDLC directory as the readme said, and the game didn't register it at all. I've taken the courtesy to include screenshots of both my main DDLC directory, as well as my Submods folder

![2021-04-27](https://user-images.githubusercontent.com/79435778/116309398-8fb91280-a75d-11eb-8647-f31ade409dc0.png)
![2021-04-27 (1)](https://user-images.githubusercontent.com/79435778/116309409-934c9980-a75d-11eb-939f-73c8da9ed0b0.png)

**Comment by Booplicate** [comment]
Extract files from the `YouTube Music` folder into this folder.

**Comment by zwartkop2** [comment]
Into which folder? The submods folder?

**Comment by Booplicate** [comment]
Into the base directory.
