### ISSUE TITLE
It softlocks the game..

### ISSUE THREAD

**Issue by CrewieAustin** [Booplicate/MAS-Submods-YouTubeMusic#20]
I wanted to find a song, but Monika sutcks on hours trying to find it. I unfortunately have to force close the game to fix this.

**Comment by d3adpan** [comment]
Same issue, on Ubuntu 20.04.3, MAS 0.12.3, YouTube Music 2.11.  Thank you!

**Comment by Booplicate** [comment]
This has been fixed, wait for next release.
