### ISSUE TITLE
Submod is not loading

### ISSUE THREAD

**Issue by Mememaster666** [Booplicate/MAS-Submods-YouTubeMusic#21]
So I have the folder in my base game directory but it won't load the mod it runs fine but that's because when I check the submods log the mod isn't there, I have reinstalled this multiple times and it's still not loading, please help. PS. have been trying to get this to work for HOURS >:(

**Comment by Booplicate** [comment]
Have you followed [the instructions I provide](https://github.com/Booplicate/MAS-Submods-YouTubeMusic#installation)?

**Comment by Mememaster666** [comment]
Yes and it didn't work either

**Comment by Mememaster666** [comment]
I just tried the master version and that didn't work either it is missing the file 'youtube.dl' I am not sure what to do.

**Comment by Booplicate** [comment]
Don't download sources, the instructions say to download from releases.

If you're missing that module, then you didn't install properly.

**Comment by Mememaster666** [comment]
I downloaded the submod from the resources first, that was the first thing I did then I put it in my DDLC folder and when I started the game the submod didn't show up it just sat there and did nothing and Monika didn't start talking about it either. So either your submod is broken or I am missing something completely.

**Comment by Mememaster666** [comment]
Bro are actually gonna help or do nothing because I would really like to try out your submod.

**Comment by Booplicate** [comment]
As I said, you did something wrong and it wasn't installed in the proper way. I cannot know what exactly went wrong. You could send screenshots of your `DDLC` and `Submods` folder, then I might tell you more.
