### ISSUE TITLE
Error when starting after installing submod

### ISSUE THREAD

**Issue by Spacexdreamer** [Booplicate/MAS-Submods-YouTubeMusic#22]
Whenever I try and load the game I run into this error.
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
    init python in ytm_utils:
  File "game/game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
ImportError: No module named ssl

**Comment by Booplicate** [comment]
You didn't install the submod properly, check [these instructions](https://github.com/Booplicate/MAS-Submods-YouTubeMusic#installation).
