### ISSUE TITLE
I can't open MAS after installing the mod

### ISSUE THREAD

**Issue by AceOfSpades719** [Booplicate/MAS-Submods-YouTubeMusic#32]
When I open MAS I get a traceback error and it's been stopping me from doing anything. 
The traceback

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
>     init python in ytm_utils:
>   File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
>     import youtube_dl
> ImportError: No module named ssl
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/Submods/YouTube Music/ytm_utils.rpy", line 164, in script
>     init python in ytm_utils:
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
>     renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
>     exec bytecode in globals, locals
>   File "game/Submods/YouTube Music/ytm_utils.rpy", line 171, in <module>
>     import youtube_dl
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\loader.py", line 711, in load_module
>     exec code in mod.__dict__
>   File "python-packages/youtube_dl/__init__.py", line 15, in <module>
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\loader.py", line 711, in load_module
>     exec code in mod.__dict__
>   File "python-packages/youtube_dl/options.py", line 8, in <module>
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\loader.py", line 711, in load_module
>     exec code in mod.__dict__
>   File "python-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\loader.py", line 711, in load_module
>     exec code in mod.__dict__
>   File "python-packages/youtube_dl/downloader/common.py", line 10, in <module>
>   File "C:\Users\Izzy Taylor\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\loader.py", line 711, in load_module
>     exec code in mod.__dict__
>   File "python-packages/youtube_dl/utils.py", line 30, in <module>
> ImportError: No module named ssl
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.9

And the error I got in the files

> 
>  I'm sorry, but errors were detected in your script. Please correct the
> errors listed below, and try again.
> 
> 
> File` "game/Submods/YouTube Music/ytm_main.rpy", line 156: u'copypaste' is not a keyword argument or valid child for the input statement.
>     copypaste True
>              ^
> 
> File "game/Submods/YouTube Music/ytm_utils.rpy", line 84: invalid syntax
>     YDL_FILENAME_FORMAT = f"%(id)s{EXTENSION}"
>                                               ^
>     
> 
> File "game/Submods/YouTube Music/ytm_utils.rpy", line 203: invalid syntax
>     def _format_log(msg: str, err: Exception|None) -> str:
>                         ^
>     
> 
> File "game/Submods/YouTube Music/ytm_utils.rpy", line 706: invalid syntax
>     def _search_music_th(raw_search_request: str):
>                                             ^
>     
> 
> Ren'Py Version: Ren'Py 6.99.12.4.2187

Can someone please fix this?

**Comment by Booplicate** [comment]
You installed source version which is WiP, never do that unless you know what you're doing.
Use releases as specified in the readme.

**Comment by AceOfSpades719** [comment]
Ah, so that where I went wrong. Thank you very much! I will attempt to fix this. I'm keeping it open just in case I have further issues

**Comment by AceOfSpades719** [comment]
It worked! Thanks a ton
