### ISSUE TITLE
Having trouble running it

### ISSUE THREAD

**Issue by Turnaroundagain** [Booplicate/MAS-Submods-YouTubeMusic#33]
I placed all the files into their folders but I get this error every time I try running it. Don't really know much about code so I'm not sure how to deal with this error.

File "game/Submods/YouTube Music/ytm_main.rpy", line 156: u'copypaste' is not a keyword argument or valid child for the input statement.
    copypaste True
             ^
File "game/Submods/YouTube Music/ytm_utils.rpy", line 84: invalid syntax
    YDL_FILENAME_FORMAT = f"%(id)s{EXTENSION}"
                                              ^
 
File "game/Submods/YouTube Music/ytm_utils.rpy", line 203: invalid syntax
    def _format_log(msg: str, err: Exception|None) -> str:
                        ^
    
File "game/Submods/YouTube Music/ytm_utils.rpy", line 706: invalid syntax
    def _search_music_th(raw_search_request: str):
                                            ^
   
Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

**Comment by Booplicate** [comment]
You didn't read or didn't follow the [readme](https://github.com/Booplicate/MAS-Submods-YouTubeMusic#installation). But also better wait for MAS Python 3 update.

**Comment by Turnaroundagain** [comment]
I'm not sure what I'm doing wrong exactly. I extracted the files and placed them in their folders but it comes up as an error still. Not sure what I'm missing.

**Comment by Booplicate** [comment]
From the readme:
![Capture](https://user-images.githubusercontent.com/53382877/206876822-cc6bdadf-6628-4b3c-8e28-eaf42612d895.PNG)

I'm not sure what files you extracted and where you placed them, but the first error tells me you downloaded the source code instead of a release. If you got a different error, send it.

**Comment by Turnaroundagain** [comment]
Fixed tysm
