### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by camnewton5555** [Booplicate/MAS-Submods-YouTubeMusic#37]
Just installed this mod. Cant get anything to play. 
here are logs
[mas_log.log](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/10375821/mas_log.log)
[submod_log.log](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/files/10375822/submod_log.log)

**Comment by Booplicate** [comment]
I'm waiting for the MAS update to release the new version of the submod #36.
