### ISSUE TITLE
mod not working.

### ISSUE THREAD

**Issue by xxunknownxxuserxx** [Booplicate/MAS-Submods-YouTubeMusic#38]
everytime i try to open the mod i get this:
Parsing the script failed.
/ytm_main.rpy", line 156: u'copypaste' is not a keyword argument or valid child for the input statement.
    copypaste True
    
/ytm_utils.rpy", line 84: invalid syntax
    YDL_FILENAME_FORMAT = f"%(id)s{EXTENSION}"
    
/ytm_utils.rpy", line 203: invalid syntax
    def _format_log(msg: str, err: Exception|None) -> str:
    
/ytm_utils.rpy", line 706: invalid syntax
    def _search_music_th(raw_search_request: str):

**Comment by Booplicate** [comment]
You didn't follow the [readme](https://github.com/Booplicate/MAS-Submods-YouTubeMusic#readme) and installed the source code.

**Comment by xxunknownxxuserxx** [comment]
You're right. Sorry, i'm new to using this site. I downloaded the newest update and i got a different error code. This is probably from my side though, i'm new to mods and stuff. I'll quote it error text down below. Do i need to have youtube downloaded for this mod?

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/submod three {AI}/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:/WINDOWS/system32/submod three {AI}/ytm_utils.rpyc", line 164, in script
  File "C:\Users\cutie\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\cutie\Downloads\ddlc-win\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/submod three {AI}/ytm_utils.rpy", line 171, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.13

**Comment by Booplicate** [comment]
You can't *download* youtube. Regardless, all you need is included in the release. Looking at this path `game/submod three {AI}/ytm_utils.rpy`, you still installed it incorrectly, otherwise it'd be inside `Submods/`. Check the readme and follow it exactly.
You'd get a structure like this:
```
DDLC/game/
    python-packages/
        *a lot of different libs*
    Submods/
        Submod Updater Plugin/
            *some assets*
            submod_updater_plugin.rpy
        YouTube Music/
            temp/
            ytm_main.rpy
            ytm_overrides.rpy
            ytm_topics.rpy
            ytm_utils.rpy
```

Also generally avoid paths with `[]` and `{}` - renpy doesn't like that.
