### ISSUE TITLE
Not working with windows or file is in the wrong place.

### ISSUE THREAD

**Issue by DrkRuna** [Booplicate/MAS-Submods-YouTubeMusic#40]
So i did follow the steps for the read me thing and i am using the current version. I just don't know if i put the file in the wrong place or if i am missing files. I did put it in the ddlc directory and then the game. which it didn't work past that point. which i tried putting the files python files separate from it which didn't work either. i also tried  searching through my files to see if i put them in the wrong place. which i don't think i did. i did think to extract the files manually which i haven't done yet but it would take time. i just need some help on what to do. My other mods did work because i did test it. so i know it is something i did wrong or something i missed.

**Comment by Booplicate** [comment]
1. tell my how it doesn't work, what is the actual issue?
2. is the submod mentioned in the submods menu (Esc > Submods)
3. send me your logs from `DDLC/log/`

**Comment by DrkRuna** [comment]
![image](https://user-images.githubusercontent.com/127463113/224405647-110b932e-567e-450a-9c9f-575ac97e52c4.png)

yes i put it under the submods.

**Comment by Booplicate** [comment]
Please, read the [instructions](https://github.com/Booplicate/MAS-Submods-YouTubeMusic#installation).

**Comment by DrkRuna** [comment]
i did. i just don't know if i am doing it wrong. i did see the youtube folder when i put it game ddlc directory but past that it doesn't go into submods for some reason. i just don't know why. as i said i tried multiple different ways to see if it would work and it didn't i am just wondering if it has to do with a specific file. i read the file/ read me thing many times and made sure that i was doing it right but it still isn't working. I can show you the files of what i have on and where everything is located at the moment if you want. if that would help.

**Comment by Booplicate** [comment]
Well, even if you did read, you didn't follow the instructions, because the 2 point tells to download the latest release and even provides a link to it.
![Capture](https://user-images.githubusercontent.com/53382877/224508296-a9a47155-37a3-416f-bc3e-63e9f465678a.PNG)
Yet you downloaded source code.

**Comment by DrkRuna** [comment]
oooooo. i see. so does it need both to work?
