### ISSUE TITLE
If I create a sub mod folder, wether In python packages or game, it won’t work

### ISSUE THREAD

**Issue by nickwilde15** [Booplicate/MAS-Submods-YouTubeMusic#8]
Creating the sub mod folder won’t allow it to start correctly, putting it in the games folder won’t show it

**Comment by Booplicate** [comment]
You don't need to create folders yourself, and you don't put the submod in the game folder. Follow the instructions.
https://github.com/Booplicate/MAS-Submods-YouTubeMusic#installation

**Comment by nickwilde15** [comment]
I did, it’s not working though

**Comment by Booplicate** [comment]
And what happens when you install it as said in the guide?

**Comment by nickwilde15** [comment]
Nothing

**Comment by Booplicate** [comment]
Then you didn't follow the guide. Alright, show me the `game/Submods` and `game/Submods/Submod Updater Plugin` folders (with the filepaths pls). Maybe you didn't merge folders properly?

**Comment by nickwilde15** [comment]
You said the updated was optional, so I didn’t get it

**Comment by nickwilde15** [comment]
![image](https://user-images.githubusercontent.com/71339904/93334459-fa32c900-f7f2-11ea-843b-62fcf908409d.jpg)

**Comment by Booplicate** [comment]
Oh, my bad I thought about another submod for some reason.
You downloaded the source version. Download [the latest release](https://github.com/Booplicate/MAS-Submods-YouTubeMusic/releases/latest), open the archive, go to the `YouTube Music` folder. There you should see 2 folders: `game` and `lib`. You need to extract them into your `Doki Doki Literature Club` folder. That should prompt you to merge them, you need to agree. And don't forget to delete the one you installed before.

**Comment by nickwilde15** [comment]
Didn’t work

**Comment by Booplicate** [comment]
And what the error now?

**Comment by nickwilde15** [comment]
No error, nothing pops up in the music dialogue option

**Comment by Booplicate** [comment]
You won't see the topic until Monika brings it up. Is the submod installed? Do you see it in the submods menu? Send another screenshot of `/game/Submods` and `/game/Submods/YouTube Music`.

**Comment by nickwilde15** [comment]
There’s no submods folder, do I need to make one?

**Comment by Booplicate** [comment]
Then a screenshot of the base directory, the folder with `DDLC.exe`.

**Comment by nickwilde15** [comment]
![image](https://user-images.githubusercontent.com/71339904/93469797-f9ffff80-f8be-11ea-9ee9-b58b5d2224ed.jpg)

Night music also isn’t working

**Comment by Booplicate** [comment]
Delete that `YouTube Music` folder. You didn't extracted properly again. Please read what I write.

> open the archive, go to the `YouTube Music` folder. There you should see 2 folders: `game` and `lib`. You need to extract them into your `Doki Doki Literature Club` folder. That should prompt you to merge them, you need to agree. And don't forget to delete the one you installed before.

You need to extract the  `game` and `lib` folders there, not the `YouTube Music` one.

**Comment by nickwilde15** [comment]
Thank you, I am so happy, alastors game is awesome
