### ISSUE TITLE
[Suggestion] Integration with script-songs.rpy?

### ISSUE THREAD

**Issue by AdeenDragon** [Booplicate/MAS-Submods-YouTubeMusic#9]
Would it be feasible for YouTubeMusic to play songs while Monika sings them?  For example, while Monika sings Wonderwall, YouTubeMusic plays https://www.youtube.com/watch?v=bx1Bh8ZvH84.

I'm pretty sure that it's possible, but I don't know if it's out of scope for the submod.

**Comment by Booplicate** [comment]
It is possible, but there are things that should be resolved:
 - need to find music w/o lyrics (what do we do if there's no such music video? what do we do with false positives that have lyric in them?)
 - music should be synchronized with Monika's speech. This may require overrides that I don't want to maintain, but if all songs were adjusted officially to follow their music speed/rhythm, then it'd not be a problem

Both of those are quite tricky, and I don't have plans to add this.

**Comment by AdeenDragon** [comment]
Those are excellent points.  In order for things to be consistent, every song that Monika sings would need an instrumental on YouTube.  In addition, it would create work that would need done every update, assuming people contributed new songs. 

The ratio of work to benefit towards Monika and the player doesn't make sense here.
